{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "mfr.fullname" . }}
  labels:
    app: {{ template "mfr.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "mfr.name" . }}
      release: {{ .Release.Name }}
  ingress: {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress: {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
